---
framework: jest
postMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
preRun:
  command:
    - env
    - node --version
    - npm i && npm run react
postRun:
  command:
    - node --version
nodeVersion: 14.17.6
version: 2.1
