---
framework: jest
postMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
preRun:
  - npm i
  - npm run react
postRun:
  - node --version
version: 2.0
